// SPDX-License-Identifier: GPL-2.0
/*
 * Copyright (c) 2020-2024 Rockchip Electronics Co., Ltd.
 *
 * Author: Zorro Liu <zorro.liu@rock-chips.com>
 */

	.text
	.file	"pvi_waveform.c"
	.globl	pvi_wf_add_custom_mode_table    // -- Begin function pvi_wf_add_custom_mode_table
	.p2align	2
	.type	pvi_wf_add_custom_mode_table,@function
	.word	2966407633                      // 0xb0cfc9d1
pvi_wf_add_custom_mode_table:           // @pvi_wf_add_custom_mode_table
// %bb.0:
	cmp	w1, #11
	b.ne	.LBB0_4
// %bb.1:
	ldrb	w8, [x0, #2]
	adrp	x9, custom_mode_table
	add	x9, x9, :lo12:custom_mode_table
	strb	w8, [x9]
	ldrb	w8, [x0, #3]
	strb	w8, [x9, #1]
	ldrb	w8, [x0, #4]
	strb	w8, [x9, #2]
	ldrb	w8, [x0, #5]
	strb	w8, [x9, #3]
	ldrb	w8, [x0, #6]
	strb	w8, [x9, #4]
	ldrb	w8, [x0, #7]
	strb	w8, [x9, #5]
	ldrb	w8, [x0, #8]
	strb	w8, [x9, #6]
	ldrb	w8, [x0, #9]
	strb	w8, [x9, #7]
	ldrb	w8, [x0, #10]
	strb	w8, [x9, #8]
	ldrb	w8, [x0]
	strb	w8, [x9, #9]
	ldrb	w8, [x0, #1]
	cmp	w8, #4
	b.eq	.LBB0_5
// %bb.2:
	cmp	w8, #5
	b.ne	.LBB0_7
// %bb.3:
	mov	w8, #32                         // =0x20
	b	.LBB0_6
.LBB0_4:
	mov	w0, #-1                         // =0xffffffff
	ret
.LBB0_5:
	mov	w8, #16                         // =0x10
.LBB0_6:
	mov	w0, wzr
	adrp	x9, custom_mode_table+12
	str	w8, [x9, :lo12:custom_mode_table+12]
	ret
.LBB0_7:
	mov	w0, wzr
	ret
.Lfunc_end0:
	.size	pvi_wf_add_custom_mode_table, .Lfunc_end0-pvi_wf_add_custom_mode_table
                                        // -- End function
	.globl	pvi_wf_get_lut                  // -- Begin function pvi_wf_get_lut
	.p2align	2
	.type	pvi_wf_get_lut,@function
	.word	4161009509                      // 0xf803f765
pvi_wf_get_lut:                         // @pvi_wf_get_lut
// %bb.0:
	str	x30, [x18], #8
	sub	sp, sp, #112
	stp	x29, x30, [sp, #16]             // 16-byte Folded Spill
	add	x29, sp, #16
	stp	x28, x27, [sp, #32]             // 16-byte Folded Spill
	stp	x26, x25, [sp, #48]             // 16-byte Folded Spill
	stp	x24, x23, [sp, #64]             // 16-byte Folded Spill
	stp	x22, x21, [sp, #80]             // 16-byte Folded Spill
	stp	x20, x19, [sp, #96]             // 16-byte Folded Spill
	mrs	x8, SP_EL0
	adrp	x20, global_waveform
	ldr	x8, [x8, #1608]
	str	x8, [sp, #8]
	ldr	x8, [x20, :lo12:global_waveform]
	str	wzr, [sp, #4]
	cbz	x8, .LBB1_11
// %bb.1:
	mov	x19, x0
	cbnz	x0, .LBB1_3
// %bb.2:
	mov	w9, #24                         // =0x18
	ldr	x9, [x9]
	cbz	x9, .LBB1_23
.LBB1_3:
	ldr	w9, [x3]
	adrp	x10, need_pic
	cmp	w1, #10
	str	w9, [x10, :lo12:need_pic]
	b.ne	.LBB1_12
// %bb.4:
	ldr	x8, [x19, #32]
	cbz	x8, .LBB1_21
// %bb.5:
	adrp	x22, pvi_wf_get_lut.sftemp
	mov	w10, #43691                     // =0xaaab
	ubfx	w11, w2, #8, #8
	ldr	w9, [x22, :lo12:pvi_wf_get_lut.sftemp]
	movk	w10, #43690, lsl #16
	mov	w12, #43692                     // =0xaaac
	asr	w9, w9, #8
	add	w9, w9, #2
	umull	x9, w9, w10
	mov	w10, #21846                     // =0x5556
	madd	w10, w11, w10, w12
	lsr	x9, x9, #33
	cmp	w9, w10, lsr #16
	b.eq	.LBB1_21
// %bb.6:
	adrp	x24, waveformdata
	and	w23, w2, #0xffff
	str	x8, [x24, :lo12:waveformdata]
	bl	epd_overlay_lut
	ldr	x11, [x20, :lo12:global_waveform]
	mov	w21, w0
	ldrb	w8, [x11, #38]
	cbz	w8, .LBB1_46
// %bb.7:
	lsr	w10, w23, #8
	mov	x9, xzr
	add	x11, x11, #48
.LBB1_8:                                // =>This Inner Loop Header: Depth=1
	ldrb	w12, [x11, x9]
	cmp	w12, w10
	b.hs	.LBB1_63
// %bb.9:                               //   in Loop: Header=BB1_8 Depth=1
	add	x9, x9, #1
	cmp	x8, x9
	b.ne	.LBB1_8
// %bb.10:
	mov	w10, #-1                        // =0xffffffff
	mov	w9, w8
	b	.LBB1_64
.LBB1_11:
	mov	w0, #-19                        // =0xffffffed
	b	.LBB1_95
.LBB1_12:
	and	w23, w2, #0xff
	mov	w9, #21846                      // =0x5556
	adrp	x10, pvi_wf_get_lut.sftemp
	mov	w11, #43692                     // =0xaaac
	madd	w12, w23, w9, w11
	ldrb	w10, [x10, :lo12:pvi_wf_get_lut.sftemp]
	adrp	x25, pvi_wf_get_lut.stype
	adrp	x24, pvi_wf_get_lut.normal_repair
	madd	w9, w10, w9, w11
	lsr	w10, w12, #16
	cmp	w10, w9, lsr #16
	b.ne	.LBB1_16
// %bb.13:
	ldr	w9, [x25, :lo12:pvi_wf_get_lut.stype]
	cmp	w9, w1
	b.ne	.LBB1_16
// %bb.14:
	ldr	w9, [x24, :lo12:pvi_wf_get_lut.normal_repair]
	ldr	w10, [x3, #8]
	cmp	w9, w10
	b.ne	.LBB1_16
// %bb.15:
	ldr	w9, [x3, #12]
	cbz	w9, .LBB1_21
.LBB1_16:
	ldr	x10, [x19, #24]
	ldrb	w9, [x8, #38]
	adrp	x21, waveformdata
	mov	x26, x3
	str	x10, [x21, :lo12:waveformdata]
	cbz	w9, .LBB1_22
// %bb.17:
	mov	x10, xzr
	add	x8, x8, #48
.LBB1_18:                               // =>This Inner Loop Header: Depth=1
	ldrb	w11, [x8, x10]
	cmp	w11, w2, uxtb
	b.hs	.LBB1_24
// %bb.19:                              //   in Loop: Header=BB1_18 Depth=1
	add	x10, x10, #1
	cmp	x9, x10
	b.ne	.LBB1_18
// %bb.20:
	mov	w8, #-1                         // =0xffffffff
	mov	w10, w9
	b	.LBB1_25
.LBB1_21:
	mov	w0, wzr
	b	.LBB1_95
.LBB1_22:
	mov	w20, wzr
	b	.LBB1_26
.LBB1_23:
	mov	w0, #-22                        // =0xffffffea
	b	.LBB1_95
.LBB1_24:
	mov	w8, w10
.LBB1_25:
	sub	w11, w10, #1
	cmp	w10, w9
	csel	w20, w11, w8, eq
.LBB1_26:
	mov	w0, w1
	mov	w27, w1
	bl	get_wf_mode_index
	and	w0, w0, #0xff
	mov	w1, w20
	bl	get_wf_frm_num
	tbnz	w0, #31, .LBB1_77
// %bb.27:
	ldr	w10, [x26, #4]
	mov	w20, w0
	mov	x8, x26
	mov	w9, w27
	cbz	w10, .LBB1_94
// %bb.28:
	cmp	w9, #7
	b.eq	.LBB1_30
// %bb.29:
	cmp	w9, #1
	b.ne	.LBB1_33
.LBB1_30:
	ldr	w22, [x8, #24]
	ldr	x21, [x21, :lo12:waveformdata]
	lsl	w9, w20, #10
	mov	w1, wzr
	cmp	w22, #0
	add	x0, x21, w9, sxtw
	cset	w8, gt
	lsl	w28, w20, w8
	sub	w8, w28, w20
	str	w28, [sp, #4]
	lsl	w8, w8, #10
	sxtw	x2, w8
	bl	memset
	cbz	w20, .LBB1_59
// %bb.31:
	cmp	w20, #1
	mov	w8, w20
	b.ne	.LBB1_47
// %bb.32:
	mov	x9, xzr
	b	.LBB1_57
.LBB1_33:
	sub	w10, w9, #13
	cmp	w10, #1
	b.hi	.LBB1_75
// %bb.34:
	ldr	x21, [x21, :lo12:waveformdata]
	ldr	w22, [x8, #8]
	mov	w1, w20
	mov	x0, x21
	bl	epd_normal_repair
	mov	w9, w27
	mov	x8, x26
	cbz	w20, .LBB1_94
// %bb.35:
	cbnz	w0, .LBB1_94
// %bb.36:
	sub	w14, w20, #5
	sub	w13, w20, #4
	sub	w12, w20, #3
	ubfiz	x11, x20, #10, #32
	ubfiz	x12, x12, #10, #32
	ubfiz	x13, x13, #10, #32
	ubfiz	x14, x14, #10, #32
	mov	x10, xzr
	mov	w15, #1                         // =0x1
	mov	w16, #2                         // =0x2
	b	.LBB1_40
.LBB1_37:                               //   in Loop: Header=BB1_40 Depth=1
	strb	w15, [x17, #991]
	mov	w0, #2                          // =0x2
	strb	w15, [x17, #959]
	strb	w15, [x17, #1023]
.LBB1_38:                               //   in Loop: Header=BB1_40 Depth=1
	strb	w0, [x17]
.LBB1_39:                               //   in Loop: Header=BB1_40 Depth=1
	ldrb	w0, [x17, #30]
	add	x10, x10, #1024
	strb	wzr, [x17, #958]
	cmp	x11, x10
	strb	wzr, [x17, #1022]
	strb	w0, [x17, #31]
	strb	w0, [x17, #63]
	strb	w0, [x17, #127]
	strb	w0, [x17, #29]
	strb	w0, [x17, #61]
	strb	w0, [x17, #125]
	ldrb	w0, [x17, #960]
	strb	wzr, [x17, #96]
	strb	wzr, [x17, #32]
	strb	w0, [x17, #961]
	strb	w0, [x17, #993]
	strb	w0, [x17, #929]
	strb	w0, [x17, #963]
	strb	w0, [x17, #995]
	strb	w0, [x17, #931]
	b.eq	.LBB1_94
.LBB1_40:                               // =>This Inner Loop Header: Depth=1
	add	x17, x21, w10, sxtw
	cbz	w22, .LBB1_39
// %bb.41:                              //   in Loop: Header=BB1_40 Depth=1
	ldrb	w0, [x17, #990]
	ldrb	w1, [x17]
	cmp	x14, x10
	strb	wzr, [x17, #990]
	strb	w0, [x17, #989]
	strb	w0, [x17, #1021]
	strb	w0, [x17, #957]
	strb	w1, [x17, #3]
	strb	w1, [x17, #35]
	strb	w1, [x17, #99]
	b.eq	.LBB1_37
// %bb.42:                              //   in Loop: Header=BB1_40 Depth=1
	cmp	x13, x10
	b.eq	.LBB1_44
// %bb.43:                              //   in Loop: Header=BB1_40 Depth=1
	cmp	x12, x10
	b.ne	.LBB1_45
.LBB1_44:                               //   in Loop: Header=BB1_40 Depth=1
	strb	w16, [x17, #991]
	mov	w0, #1                          // =0x1
	strb	w16, [x17, #959]
	strb	w16, [x17, #1023]
	b	.LBB1_38
.LBB1_45:                               //   in Loop: Header=BB1_40 Depth=1
	mov	w0, wzr
	strb	wzr, [x17, #991]
	strb	wzr, [x17, #959]
	strb	wzr, [x17, #1023]
	b	.LBB1_38
.LBB1_46:
	mov	w20, wzr
	b	.LBB1_65
.LBB1_47:
	sub	x10, x8, #1
	add	x9, x21, #992
	lsl	x11, x10, #10
	add	x12, x9, x11
	cmp	x12, x9
	mov	x9, xzr
	b.lo	.LBB1_57
// %bb.48:
	add	x12, x21, #1022
	add	x13, x12, x11
	cmp	x13, x12
	b.lo	.LBB1_57
// %bb.49:
	add	x12, x21, #928
	add	x13, x12, x11
	cmp	x13, x12
	b.lo	.LBB1_57
// %bb.50:
	add	x12, x21, #958
	add	x13, x12, x11
	cmp	x13, x12
	b.lo	.LBB1_57
// %bb.51:
	add	x12, x21, #990
	add	x13, x12, x11
	cmp	x13, x12
	b.lo	.LBB1_57
// %bb.52:
	add	x11, x21, x11
	cmp	x11, x21
	b.lo	.LBB1_57
// %bb.53:
	lsr	x10, x10, #21
	cbnz	x10, .LBB1_57
// %bb.54:
	and	x9, x8, #0x7ffffffe
	mov	w10, #1024                      // =0x400
	mov	x11, x9
.LBB1_55:                               // =>This Inner Loop Header: Depth=1
	sub	w13, w10, #1024
	add	x12, x21, w10, sxtw
	subs	x11, x11, #2
	add	x13, x21, w13, sxtw
	add	w10, w10, #2048
	strb	wzr, [x12, #992]
	strb	wzr, [x12, #1022]
	strb	wzr, [x13, #992]
	strb	wzr, [x13, #1022]
	strb	wzr, [x13, #928]
	strb	wzr, [x12, #928]
	strb	wzr, [x13, #958]
	strb	wzr, [x12, #958]
	strb	wzr, [x13]
	strb	wzr, [x12]
	strb	wzr, [x13, #990]
	strb	wzr, [x12, #990]
	b.ne	.LBB1_55
// %bb.56:
	cmp	x9, x8
	b.eq	.LBB1_59
.LBB1_57:
	lsl	w10, w9, #10
	sub	x8, x8, x9
.LBB1_58:                               // =>This Inner Loop Header: Depth=1
	add	x9, x21, w10, sxtw
	subs	x8, x8, #1
	add	w10, w10, #1024
	strb	wzr, [x9, #992]
	strb	wzr, [x9, #1022]
	strb	wzr, [x9, #928]
	strb	wzr, [x9, #958]
	strb	wzr, [x9]
	strb	wzr, [x9, #990]
	b.ne	.LBB1_58
.LBB1_59:
	add	x2, sp, #4
	mov	x0, x21
	mov	w1, w20
	mov	w3, w22
	bl	epd_gray2_last_repair
	mov	x8, x26
	mov	w9, w27
	cbnz	w0, .LBB1_94
// %bb.60:
	sub	w10, w28, #1
	cmp	w22, w10
	csel	w10, w22, w10, lt
	cmp	w10, #1
	b.lt	.LBB1_94
// %bb.61:
	mov	w11, wzr
	mov	w12, #1                         // =0x1
	mov	w13, #2                         // =0x2
	mov	w14, w28
	mov	w15, w10
.LBB1_62:                               // =>This Inner Loop Header: Depth=1
	lsl	w16, w11, #10
	sdiv	w11, w14, w10
	subs	w15, w15, #1
	add	w14, w14, w28
	add	x16, x21, w16, sxtw
	strb	w12, [x16, #992]
	strb	w12, [x16, #928]
	strb	w13, [x16, #1022]
	strb	w13, [x16, #958]
	b.ne	.LBB1_62
	b	.LBB1_94
.LBB1_63:
	mov	w10, w9
.LBB1_64:
	sub	w11, w9, #1
	cmp	w9, w8
	csel	w20, w11, w10, eq
.LBB1_65:
	mov	w0, w21
	bl	get_wf_mode_index
	and	w0, w0, #0xff
	mov	w1, w20
	bl	get_wf_frm_num
	tbnz	w0, #31, .LBB1_77
// %bb.66:
	mov	w20, w0
	cmp	w21, #1
	b.ne	.LBB1_74
// %bb.67:
	ldr	x21, [x24, :lo12:waveformdata]
	cbz	w20, .LBB1_72
// %bb.68:
	mov	w8, wzr
	mov	x9, xzr
	mov	w10, w20
	add	x11, x21, #31
	add	x12, x21, #992
.LBB1_69:                               // =>This Loop Header: Depth=1
                                        //     Child Loop BB1_70 Depth 2
	sxtw	x14, w8
	mov	x15, #-16                       // =0xfffffffffffffff0
	add	x13, x11, x14
	add	x14, x12, x14
.LBB1_70:                               //   Parent Loop BB1_69 Depth=1
                                        // =>  This Inner Loop Header: Depth=2
	ldurb	w16, [x13, #-1]
	add	x15, x15, #16
	cmp	x15, #224
	strb	w16, [x13]
	sturb	w16, [x13, #-2]
	add	x13, x13, #64
	ldurb	w16, [x14, #-32]
	sturb	w16, [x14, #-64]
	strb	w16, [x14], #2
	b.lo	.LBB1_70
// %bb.71:                              //   in Loop: Header=BB1_69 Depth=1
	add	x9, x9, #1
	add	w8, w8, #1024
	cmp	x9, x10
	b.ne	.LBB1_69
.LBB1_72:
	mov	x0, x21
	mov	w1, w20
	bl	epd_overlay_gray2_repair
	cbnz	w0, .LBB1_74
// %bb.73:
	lsl	w8, w20, #10
	mov	w9, #2                          // =0x2
	sub	w8, w8, #2048
	add	x8, x21, w8, sxtw
	strb	w9, [x8, #991]
	strb	w9, [x8, #959]
	strb	w9, [x8, #1023]
.LBB1_74:
	ldrb	w8, [x22, :lo12:pvi_wf_get_lut.sftemp]
	and	w9, w23, #0xff00
	str	w20, [x19, #4]
	mov	w0, #2                          // =0x2
	orr	w8, w8, w9
	str	w8, [x22, :lo12:pvi_wf_get_lut.sftemp]
	b	.LBB1_95
.LBB1_75:
	sub	w10, w9, #5
	cmp	w10, #1
	b.hi	.LBB1_78
// %bb.76:
	ldr	x0, [x19, #24]
	ldr	w2, [x8, #12]
	mov	w1, w20
	bl	pvi_wf_regal_fix
	mov	w9, w27
	mov	x8, x26
	b	.LBB1_94
.LBB1_77:
	adrp	x0, .L.str
	add	x0, x0, :lo12:.L.str
	bl	_printk
	mov	w0, #-5                         // =0xfffffffb
	b	.LBB1_95
.LBB1_78:
	cmp	w9, #15
	b.ne	.LBB1_94
// %bb.79:
	cbz	w20, .LBB1_94
// %bb.80:
	ldr	x10, [x21, :lo12:waveformdata]
	cmp	w20, #1
	mov	w11, w20
	b.ne	.LBB1_82
// %bb.81:
	mov	x12, xzr
	b	.LBB1_92
.LBB1_82:
	sub	x13, x11, #1
	add	x12, x10, #958
	lsl	x14, x13, #10
	add	x15, x12, x14
	cmp	x15, x12
	mov	x12, xzr
	b.lo	.LBB1_92
// %bb.83:
	add	x15, x10, #990
	add	x16, x15, x14
	cmp	x16, x15
	b.lo	.LBB1_92
// %bb.84:
	add	x15, x10, #1022
	add	x16, x15, x14
	cmp	x16, x15
	b.lo	.LBB1_92
// %bb.85:
	add	x15, x10, #991
	add	x16, x15, x14
	cmp	x16, x15
	b.lo	.LBB1_92
// %bb.86:
	add	x15, x10, #1023
	add	x16, x15, x14
	cmp	x16, x15
	b.lo	.LBB1_92
// %bb.87:
	add	x15, x10, #957
	add	x14, x15, x14
	cmp	x14, x15
	b.lo	.LBB1_92
// %bb.88:
	lsr	x13, x13, #21
	cbnz	x13, .LBB1_92
// %bb.89:
	and	x12, x11, #0x7ffffffe
	mov	w13, #1024                      // =0x400
	mov	x14, x12
.LBB1_90:                               // =>This Inner Loop Header: Depth=1
	sub	w16, w13, #1024
	add	x15, x10, w13, sxtw
	subs	x14, x14, #2
	add	x16, x10, w16, sxtw
	add	w13, w13, #2048
	ldrb	w17, [x15, #957]
	ldrb	w0, [x16, #957]
	strb	w17, [x15, #958]
	strb	w17, [x15, #990]
	strb	w17, [x15, #1022]
	strb	w0, [x16, #958]
	strb	w0, [x16, #990]
	strb	w0, [x16, #1022]
	strb	w0, [x16, #991]
	strb	w17, [x15, #991]
	strb	w0, [x16, #1023]
	strb	w17, [x15, #1023]
	b.ne	.LBB1_90
// %bb.91:
	cmp	x12, x11
	b.eq	.LBB1_94
.LBB1_92:
	lsl	w13, w12, #10
	sub	x11, x11, x12
.LBB1_93:                               // =>This Inner Loop Header: Depth=1
	add	x12, x10, w13, sxtw
	subs	x11, x11, #1
	add	w13, w13, #1024
	ldrb	w14, [x12, #957]
	strb	w14, [x12, #958]
	strb	w14, [x12, #990]
	strb	w14, [x12, #1022]
	strb	w14, [x12, #991]
	strb	w14, [x12, #1023]
	b.ne	.LBB1_93
.LBB1_94:
	str	w20, [x19]
	ldr	w10, [sp, #4]
	adrp	x11, pvi_wf_get_lut.sftemp
	add	x11, x11, :lo12:pvi_wf_get_lut.sftemp
	mov	w0, #1                          // =0x1
	str	w9, [x25, :lo12:pvi_wf_get_lut.stype]
	ldrb	w12, [x11, #1]
	str	w10, [x19, #8]
	ldr	w8, [x8, #8]
	orr	w10, w23, w12, lsl #8
	str	w8, [x24, :lo12:pvi_wf_get_lut.normal_repair]
	str	w10, [x11]
.LBB1_95:
	mrs	x8, SP_EL0
	ldr	x8, [x8, #1608]
	ldr	x9, [sp, #8]
	cmp	x8, x9
	b.ne	.LBB1_97
// %bb.96:
	ldp	x20, x19, [sp, #96]             // 16-byte Folded Reload
	ldp	x22, x21, [sp, #80]             // 16-byte Folded Reload
	ldp	x24, x23, [sp, #64]             // 16-byte Folded Reload
	ldp	x26, x25, [sp, #48]             // 16-byte Folded Reload
	ldp	x28, x27, [sp, #32]             // 16-byte Folded Reload
	ldp	x29, x30, [sp, #16]             // 16-byte Folded Reload
	add	sp, sp, #112
	ldr	x30, [x18, #-8]!
	ret
.LBB1_97:
	bl	__stack_chk_fail
.Lfunc_end1:
	.size	pvi_wf_get_lut, .Lfunc_end1-pvi_wf_get_lut
                                        // -- End function
	.p2align	2                               // -- Begin function get_wf_mode_index
	.type	get_wf_mode_index,@function
get_wf_mode_index:                      // @get_wf_mode_index
// %bb.0:
	cmp	w0, #16
	b.hs	.LBB2_28
// %bb.1:
	sub	w8, w0, #11
	cmp	w8, #5
	b.hs	.LBB2_3
// %bb.2:
	adrp	x9, .Lswitch.table.get_wf_mode_index
	add	x9, x9, :lo12:.Lswitch.table.get_wf_mode_index
	ldr	x8, [x9, w8, uxtw #3]
	b	.LBB2_4
.LBB2_3:
	mov	w8, w0
.LBB2_4:
	adrp	x9, global_waveform
	ldr	x9, [x9, :lo12:global_waveform]
	ldrb	w9, [x9, #16]
	cmp	w9, #31
	b.le	.LBB2_9
// %bb.5:
	cmp	w9, #71
	b.gt	.LBB2_14
// %bb.6:
	cmp	w9, #32
	b.eq	.LBB2_21
// %bb.7:
	cmp	w9, #35
	b.eq	.LBB2_23
// %bb.8:
	cmp	w9, #67
	b.eq	.LBB2_13
	b	.LBB2_27
.LBB2_9:
	cmp	w9, #21
	b.le	.LBB2_18
// %bb.10:
	cmp	w9, #22
	b.eq	.LBB2_25
// %bb.11:
	cmp	w9, #24
	b.eq	.LBB2_21
// %bb.12:
	cmp	w9, #25
	b.ne	.LBB2_27
.LBB2_13:
	adrp	x9, pvi_mode_table+27
	add	x9, x9, :lo12:pvi_mode_table+27
	ldrb	w0, [x9, x8]
	ret
.LBB2_14:
	cmp	w9, #72
	b.eq	.LBB2_26
// %bb.15:
	cmp	w9, #84
	b.eq	.LBB2_24
// %bb.16:
	cmp	w9, #114
	b.ne	.LBB2_27
// %bb.17:
	adrp	x9, pvi_mode_table+63
	add	x9, x9, :lo12:pvi_mode_table+63
	ldrb	w0, [x9, x8]
	ret
.LBB2_18:
	cmp	w9, #9
	b.eq	.LBB2_22
// %bb.19:
	cmp	w9, #18
	b.ne	.LBB2_27
// %bb.20:
	adrp	x9, pvi_mode_table+9
	add	x9, x9, :lo12:pvi_mode_table+9
	ldrb	w0, [x9, x8]
	ret
.LBB2_21:
	adrp	x9, pvi_mode_table+72
	add	x9, x9, :lo12:pvi_mode_table+72
	ldrb	w0, [x9, x8]
	ret
.LBB2_22:
	adrp	x9, pvi_mode_table
	add	x9, x9, :lo12:pvi_mode_table
	ldrb	w0, [x9, x8]
	ret
.LBB2_23:
	adrp	x9, pvi_mode_table+36
	add	x9, x9, :lo12:pvi_mode_table+36
	ldrb	w0, [x9, x8]
	ret
.LBB2_24:
	adrp	x9, pvi_mode_table+54
	add	x9, x9, :lo12:pvi_mode_table+54
	ldrb	w0, [x9, x8]
	ret
.LBB2_25:
	adrp	x9, pvi_mode_table+18
	add	x9, x9, :lo12:pvi_mode_table+18
	ldrb	w0, [x9, x8]
	ret
.LBB2_26:
	adrp	x9, pvi_mode_table+45
	add	x9, x9, :lo12:pvi_mode_table+45
	ldrb	w0, [x9, x8]
	ret
.LBB2_27:
	adrp	x10, custom_mode_table
	add	x10, x10, :lo12:custom_mode_table
	ldrb	w11, [x10, #9]
	cmp	w9, w11
	adrp	x9, pvi_mode_table+72
	add	x9, x9, :lo12:pvi_mode_table+72
	csel	x9, x10, x9, eq
	ldrb	w0, [x9, x8]
	ret
.LBB2_28:
	str	x30, [x18], #8
	stp	x29, x30, [sp, #-16]!           // 16-byte Folded Spill
	adrp	x0, .L.str.3
	add	x0, x0, :lo12:.L.str.3
	mov	x29, sp
	bl	_printk
	mov	w0, #255                        // =0xff
	ldp	x29, x30, [sp], #16             // 16-byte Folded Reload
	ldr	x30, [x18, #-8]!
	ret
.Lfunc_end2:
	.size	get_wf_mode_index, .Lfunc_end2-get_wf_mode_index
                                        // -- End function
	.p2align	2                               // -- Begin function get_wf_frm_num
	.type	get_wf_frm_num,@function
get_wf_frm_num:                         // @get_wf_frm_num
// %bb.0:
	str	x30, [x18], #8
	stp	x29, x30, [sp, #-64]!           // 16-byte Folded Spill
	adrp	x8, global_waveform
	str	x23, [sp, #16]                  // 8-byte Folded Spill
	mov	x29, sp
	ldr	x15, [x8, :lo12:global_waveform]
	stp	x22, x21, [sp, #32]             // 16-byte Folded Spill
	stp	x20, x19, [sp, #48]             // 16-byte Folded Spill
	ldrb	w8, [x15, #32]
	add	x8, x15, x8
	add	x8, x8, w0, uxtw #2
	ldrb	w9, [x8]
	ldrb	w10, [x8, #1]
	ldrb	w11, [x8, #2]
	ldrb	w12, [x8, #3]
	add	w9, w10, w9
	add	w9, w9, w11
	cmp	w12, w9, uxtb
	b.ne	.LBB3_26
// %bb.1:
	ldr	w8, [x8]
	lsl	w9, w1, #2
	and	x8, x8, #0xffffff
	add	x8, x15, x8
	add	x14, x8, w9, sxtw
	ldrb	w8, [x14]
	ldrb	w9, [x14, #1]
	ldrb	w10, [x14, #2]
	ldrb	w11, [x14, #3]
	add	w8, w9, w8
	add	w8, w8, w10
	cmp	w11, w8, uxtb
	b.ne	.LBB3_27
// %bb.2:
	adrp	x19, waveformdata
	ldr	x8, [x19, :lo12:waveformdata]
	cbz	x8, .LBB3_29
// %bb.3:
	adrp	x20, maxpic
	adrp	x21, need_pic
	ldr	w14, [x14]
	ldr	w9, [x20, :lo12:maxpic]
	ldr	w10, [x21, :lo12:need_pic]
	mov	w13, wzr
	and	x1, x14, #0xffffff
	mov	w11, wzr
	mov	w0, wzr
	cmp	w9, #16
	mov	w12, wzr
	add	x15, x15, x1
	cset	w16, eq
	cmp	w10, #32
	cset	w17, eq
	ands	w14, w16, w17
	mov	w16, #5                         // =0x5
	mov	w17, #1                         // =0x1
	cinc	w16, w16, ne
	b	.LBB3_6
.LBB3_4:                                //   in Loop: Header=BB3_6 Depth=1
	add	w11, w11, #2
	mov	w17, #1                         // =0x1
.LBB3_5:                                //   in Loop: Header=BB3_6 Depth=1
	cmp	w0, #254
	b.hi	.LBB3_18
.LBB3_6:                                // =>This Loop Header: Depth=1
                                        //     Child Loop BB3_16 Depth 2
	ldrb	w3, [x15, w11, uxtw]
	cmp	w3, #252
	b.eq	.LBB3_11
// %bb.7:                               //   in Loop: Header=BB3_6 Depth=1
	cmp	w3, #255
	b.eq	.LBB3_19
// %bb.8:                               //   in Loop: Header=BB3_6 Depth=1
	tbnz	w17, #0, .LBB3_12
.LBB3_9:                                //   in Loop: Header=BB3_6 Depth=1
	lsl	w17, w12, w14
	lsl	w1, w13, w16
	add	w2, w13, #1
	lsl	w2, w2, w16
	and	w4, w3, #0x3
	add	w11, w11, #1
	add	w17, w17, w0, lsl #10
	add	w1, w17, w1
	add	w2, w17, w2
	strb	w4, [x8, w1, uxtw]
	add	w1, w13, #2
	ubfx	w4, w3, #2, #2
	lsl	w1, w1, w16
	strb	w4, [x8, w2, uxtw]
	add	w2, w13, #3
	lsl	w2, w2, w16
	ubfx	w4, w3, #4, #2
	add	w13, w13, #4
	add	w1, w17, w1
	cmp	w13, w9
	strb	w4, [x8, w1, uxtw]
	lsr	w1, w3, #6
	add	w17, w17, w2
	strb	w1, [x8, w17, uxtw]
	mov	w17, wzr
	b.lo	.LBB3_5
// %bb.10:                              //   in Loop: Header=BB3_6 Depth=1
	add	w1, w12, #1
	mov	w13, wzr
	cmp	w1, w9
	csinc	w12, wzr, w12, hs
	cinc	w0, w0, hs
	b	.LBB3_5
.LBB3_11:                               //   in Loop: Header=BB3_6 Depth=1
	add	w11, w11, #1
	ldrb	w3, [x15, w11, uxtw]
	tbnz	w17, #0, .LBB3_9
.LBB3_12:                               //   in Loop: Header=BB3_6 Depth=1
	lsl	w17, w12, w14
	add	w1, w13, #1
	lsl	w2, w13, w16
	lsl	w5, w1, w16
	ubfx	w1, w3, #2, #2
	add	w6, w13, #2
	add	w4, w17, w0, lsl #10
	add	w7, w13, #3
	and	w17, w3, #0x3
	lsl	w6, w6, w16
	add	w13, w13, #4
	add	w2, w4, w2
	add	w5, w4, w5
	cmp	w13, w9
	strb	w17, [x8, w2, uxtw]
	ubfx	w2, w3, #4, #2
	lsr	w3, w3, #6
	strb	w1, [x8, w5, uxtw]
	lsl	w5, w7, w16
	add	w6, w4, w6
	strb	w2, [x8, w6, uxtw]
	add	w4, w4, w5
	strb	w3, [x8, w4, uxtw]
	b.lo	.LBB3_14
// %bb.13:                              //   in Loop: Header=BB3_6 Depth=1
	add	w4, w12, #1
	mov	w13, wzr
	cmp	w4, w9
	csinc	w12, wzr, w12, hs
	cinc	w0, w0, hs
.LBB3_14:                               //   in Loop: Header=BB3_6 Depth=1
	add	w4, w11, #1
	ldrb	w4, [x15, w4, uxtw]
	cbnz	w4, .LBB3_16
	b	.LBB3_4
.LBB3_15:                               //   in Loop: Header=BB3_16 Depth=2
	sub	w4, w4, #1
	tst	w4, #0xff
	b.eq	.LBB3_4
.LBB3_16:                               //   Parent Loop BB3_6 Depth=1
                                        // =>  This Inner Loop Header: Depth=2
	lsl	w5, w12, w14
	lsl	w7, w13, w16
	add	w6, w13, #1
	add	w22, w13, #2
	lsl	w6, w6, w16
	add	w23, w13, #3
	add	w5, w5, w0, lsl #10
	lsl	w22, w22, w16
	add	w13, w13, #4
	cmp	w13, w9
	add	w7, w5, w7
	add	w6, w5, w6
	strb	w17, [x8, w7, uxtw]
	lsl	w7, w23, w16
	strb	w1, [x8, w6, uxtw]
	add	w6, w5, w22
	add	w5, w5, w7
	strb	w2, [x8, w6, uxtw]
	strb	w3, [x8, w5, uxtw]
	b.lo	.LBB3_15
// %bb.17:                              //   in Loop: Header=BB3_16 Depth=2
	add	w5, w12, #1
	mov	w13, wzr
	cmp	w5, w9
	csinc	w12, wzr, w12, hs
	cinc	w0, w0, hs
	b	.LBB3_15
.LBB3_18:
	adrp	x8, .L.str.6
	add	x8, x8, :lo12:.L.str.6
	mov	w22, w0
	mov	x0, x8
	bl	_printk
	ldr	w9, [x20, :lo12:maxpic]
	ldr	w10, [x21, :lo12:need_pic]
	mov	w0, w22
.LBB3_19:
	cmp	w9, #32
	b.ne	.LBB3_31
// %bb.20:
	cmp	w10, #16
	b.ne	.LBB3_31
// %bb.21:
	cbz	w0, .LBB3_31
// %bb.22:
	ldr	x11, [x19, :lo12:waveformdata]
	mov	w8, wzr
	mov	w9, wzr
	add	x10, x11, #7
	add	x11, x11, #16
.LBB3_23:                               // =>This Loop Header: Depth=1
                                        //     Child Loop BB3_24 Depth 2
	mov	w13, w8
	mov	x14, #-2                        // =0xfffffffffffffffe
	add	x12, x10, x13
	add	x13, x11, x13
.LBB3_24:                               //   Parent Loop BB3_23 Depth=1
                                        // =>  This Inner Loop Header: Depth=2
	ldurb	w15, [x13, #-16]
	add	x14, x14, #2
	cmp	x14, #30
	sturb	w15, [x12, #-7]
	ldurb	w15, [x13, #-14]
	sturb	w15, [x12, #-6]
	ldurb	w15, [x13, #-12]
	sturb	w15, [x12, #-5]
	ldurb	w15, [x13, #-10]
	sturb	w15, [x12, #-4]
	ldurb	w15, [x13, #-8]
	sturb	w15, [x12, #-3]
	ldurb	w15, [x13, #-6]
	sturb	w15, [x12, #-2]
	ldurb	w15, [x13, #-4]
	sturb	w15, [x12, #-1]
	ldurb	w15, [x13, #-2]
	strb	w15, [x12]
	ldrb	w15, [x13]
	strb	w15, [x12, #1]
	ldrb	w15, [x13, #2]
	strb	w15, [x12, #2]
	ldrb	w15, [x13, #4]
	strb	w15, [x12, #3]
	ldrb	w15, [x13, #6]
	strb	w15, [x12, #4]
	ldrb	w15, [x13, #8]
	strb	w15, [x12, #5]
	ldrb	w15, [x13, #10]
	strb	w15, [x12, #6]
	ldrb	w15, [x13, #12]
	strb	w15, [x12, #7]
	ldrb	w15, [x13, #14]
	add	x13, x13, #64
	strb	w15, [x12, #8]
	add	x12, x12, #32
	b.lo	.LBB3_24
// %bb.25:                              //   in Loop: Header=BB3_23 Depth=1
	add	w9, w9, #1
	add	w8, w8, #1024
	cmp	w0, w9, uxtb
	b.hi	.LBB3_23
	b	.LBB3_31
.LBB3_26:
	adrp	x0, .L.str.4
	add	x0, x0, :lo12:.L.str.4
	adrp	x1, .L__func__.get_wf_frm_num
	add	x1, x1, :lo12:.L__func__.get_wf_frm_num
	mov	w2, #268                        // =0x10c
	b	.LBB3_28
.LBB3_27:
	adrp	x0, .L.str.4
	add	x0, x0, :lo12:.L.str.4
	adrp	x1, .L__func__.get_wf_frm_num
	add	x1, x1, :lo12:.L__func__.get_wf_frm_num
	mov	w2, #275                        // =0x113
.LBB3_28:
	bl	_printk
	b	.LBB3_30
.LBB3_29:
	adrp	x0, .L.str.5
	add	x0, x0, :lo12:.L.str.5
	bl	_printk
.LBB3_30:
	mov	w0, #-22                        // =0xffffffea
.LBB3_31:
	ldp	x20, x19, [sp, #48]             // 16-byte Folded Reload
	ldr	x23, [sp, #16]                  // 8-byte Folded Reload
	ldp	x22, x21, [sp, #32]             // 16-byte Folded Reload
	ldp	x29, x30, [sp], #64             // 16-byte Folded Reload
	ldr	x30, [x18, #-8]!
	ret
.Lfunc_end3:
	.size	get_wf_frm_num, .Lfunc_end3-get_wf_frm_num
                                        // -- End function
	.p2align	2                               // -- Begin function pvi_wf_regal_fix
	.type	pvi_wf_regal_fix,@function
pvi_wf_regal_fix:                       // @pvi_wf_regal_fix
// %bb.0:
	str	x30, [x18], #8
	stp	x29, x30, [sp, #-32]!           // 16-byte Folded Spill
	str	x19, [sp, #16]                  // 8-byte Folded Spill
	mov	w19, w1
	mov	x29, sp
	tbz	w2, #1, .LBB4_4
// %bb.1:
	cmp	w19, #1
	b.lt	.LBB4_4
// %bb.2:
	ubfiz	x8, x19, #10, #32
	mov	x9, xzr
.LBB4_3:                                // =>This Inner Loop Header: Depth=1
	add	x10, x0, w9, sxtw
	add	x9, x9, #1024
	ldrb	w11, [x10, #991]
	ldrb	w12, [x10, #989]
	strb	wzr, [x10]
	eor	w13, w11, #0x3
	cmp	w11, #0
	eor	w11, w12, #0x3
	csel	w13, wzr, w13, eq
	cmp	w12, #0
	csel	w11, wzr, w11, eq
	cmp	x8, x9
	strb	w13, [x10, #1]
	strb	w11, [x10, #3]
	b.ne	.LBB4_3
.LBB4_4:
	cmp	w19, #1
	b.lt	.LBB4_21
// %bb.5:
	mov	w8, w19
	mov	x9, xzr
	ubfiz	x10, x8, #10, #32
	mov	w8, w19
.LBB4_6:                                // =>This Inner Loop Header: Depth=1
	add	x11, x0, w9, sxtw
	add	x9, x9, #1024
	cmp	x10, x9
	ldrb	w12, [x11, #30]
	ldrb	w13, [x11, #94]
	strb	wzr, [x11, #96]
	strb	wzr, [x11, #32]
	strb	w12, [x11, #31]
	strb	w12, [x11, #29]
	ldrb	w12, [x11, #158]
	strb	w13, [x11, #95]
	strb	w13, [x11, #93]
	ldrb	w13, [x11, #222]
	strb	w12, [x11, #159]
	strb	w12, [x11, #157]
	ldrb	w12, [x11, #286]
	strb	w13, [x11, #223]
	strb	w13, [x11, #221]
	ldrb	w13, [x11, #350]
	strb	w12, [x11, #287]
	strb	w12, [x11, #285]
	ldrb	w12, [x11, #414]
	strb	w13, [x11, #351]
	strb	w13, [x11, #349]
	ldrb	w13, [x11, #478]
	strb	w12, [x11, #415]
	strb	w12, [x11, #413]
	ldrb	w12, [x11, #542]
	strb	w13, [x11, #479]
	strb	w13, [x11, #477]
	ldrb	w13, [x11, #606]
	strb	w12, [x11, #543]
	strb	w12, [x11, #541]
	ldrb	w12, [x11, #670]
	strb	w13, [x11, #607]
	strb	w13, [x11, #605]
	ldrb	w13, [x11, #734]
	strb	w12, [x11, #671]
	strb	w12, [x11, #669]
	ldrb	w12, [x11, #798]
	strb	w13, [x11, #735]
	strb	w13, [x11, #733]
	ldrb	w13, [x11, #862]
	strb	w12, [x11, #799]
	strb	w12, [x11, #797]
	ldrb	w12, [x11, #926]
	strb	w13, [x11, #863]
	strb	w13, [x11, #861]
	ldrb	w13, [x11, #960]
	strb	w12, [x11, #927]
	strb	w12, [x11, #925]
	ldrb	w12, [x11, #896]
	strb	w13, [x11, #963]
	strb	w13, [x11, #961]
	ldrb	w13, [x11, #832]
	strb	w12, [x11, #899]
	strb	w12, [x11, #897]
	ldrb	w12, [x11, #768]
	strb	w13, [x11, #835]
	strb	w13, [x11, #833]
	ldrb	w13, [x11, #704]
	strb	w12, [x11, #771]
	strb	w12, [x11, #769]
	ldrb	w12, [x11, #640]
	strb	w13, [x11, #707]
	strb	w13, [x11, #705]
	ldrb	w13, [x11, #576]
	strb	w12, [x11, #643]
	strb	w12, [x11, #641]
	ldrb	w12, [x11, #512]
	strb	w13, [x11, #579]
	strb	w13, [x11, #577]
	ldrb	w13, [x11, #448]
	strb	w12, [x11, #515]
	strb	w12, [x11, #513]
	ldrb	w12, [x11, #384]
	strb	w13, [x11, #451]
	strb	w13, [x11, #449]
	ldrb	w13, [x11, #320]
	strb	w12, [x11, #387]
	strb	w12, [x11, #385]
	ldrb	w12, [x11, #256]
	strb	w13, [x11, #323]
	strb	w13, [x11, #321]
	ldrb	w13, [x11, #192]
	strb	w12, [x11, #259]
	strb	w12, [x11, #257]
	ldrb	w12, [x11, #128]
	strb	w13, [x11, #195]
	strb	w13, [x11, #193]
	ldrb	w13, [x11, #64]
	strb	w12, [x11, #131]
	strb	w12, [x11, #129]
	strb	w13, [x11, #67]
	strb	w13, [x11, #65]
	b.ne	.LBB4_6
// %bb.7:
	tbnz	w2, #0, .LBB4_21
// %bb.8:
	cmp	w19, #1
	b.lt	.LBB4_21
// %bb.9:
	b.ne	.LBB4_11
// %bb.10:
	mov	x9, xzr
	b	.LBB4_19
.LBB4_11:
	sub	x10, x8, #1
	add	x9, x0, #991
	lsl	x11, x10, #10
	add	x12, x9, x11
	cmp	x12, x9
	mov	x9, xzr
	b.lo	.LBB4_19
// %bb.12:
	add	x12, x0, #989
	add	x13, x12, x11
	cmp	x13, x12
	b.lo	.LBB4_19
// %bb.13:
	add	x12, x0, #1023
	add	x13, x12, x11
	cmp	x13, x12
	b.lo	.LBB4_19
// %bb.14:
	add	x11, x0, x11
	cmp	x11, x0
	b.lo	.LBB4_19
// %bb.15:
	lsr	x10, x10, #21
	cbnz	x10, .LBB4_19
// %bb.16:
	and	x9, x8, #0x3ffffe
	mov	w10, #1024                      // =0x400
	mov	x11, x9
.LBB4_17:                               // =>This Inner Loop Header: Depth=1
	sub	w12, w10, #1024
	add	x13, x0, w10, sxtw
	add	w10, w10, #2048
	add	x12, x0, w12, sxtw
	ldrb	w15, [x13]
	strb	wzr, [x13, #991]
	ldrb	w14, [x12]
	strb	wzr, [x12, #991]
	strb	wzr, [x12, #989]
	eor	w16, w14, #0x3
	cmp	w14, #0
	eor	w14, w15, #0x3
	csel	w16, wzr, w16, eq
	cmp	w15, #0
	strb	wzr, [x13, #989]
	csel	w14, wzr, w14, eq
	subs	x11, x11, #2
	strb	w16, [x12, #1023]
	strb	w14, [x13, #1023]
	b.ne	.LBB4_17
// %bb.18:
	cmp	x9, x8
	b.eq	.LBB4_21
.LBB4_19:
	lsl	w10, w9, #10
	sub	x8, x8, x9
.LBB4_20:                               // =>This Inner Loop Header: Depth=1
	add	x9, x0, w10, sxtw
	add	w10, w10, #1024
	ldrb	w11, [x9]
	strb	wzr, [x9, #991]
	strb	wzr, [x9, #989]
	eor	w12, w11, #0x3
	cmp	w11, #0
	csel	w11, wzr, w12, eq
	subs	x8, x8, #1
	strb	w11, [x9, #1023]
	b.ne	.LBB4_20
.LBB4_21:
	mov	w1, w19
	bl	epd_regal_repair
	mov	w0, w19
	ldr	x19, [sp, #16]                  // 8-byte Folded Reload
	ldp	x29, x30, [sp], #32             // 16-byte Folded Reload
	ldr	x30, [x18, #-8]!
	ret
.Lfunc_end4:
	.size	pvi_wf_regal_fix, .Lfunc_end4-pvi_wf_regal_fix
                                        // -- End function
	.globl	pvi_wf_get_original_lut         // -- Begin function pvi_wf_get_original_lut
	.p2align	2
	.type	pvi_wf_get_original_lut,@function
	.word	2908290955                      // 0xad58ff8b
pvi_wf_get_original_lut:                // @pvi_wf_get_original_lut
// %bb.0:
	adrp	x8, global_waveform
	ldr	x10, [x8, :lo12:global_waveform]
	cbz	x10, .LBB5_8
// %bb.1:
	str	x30, [x18], #8
	stp	x29, x30, [sp, #-32]!           // 16-byte Folded Spill
	stp	x20, x19, [sp, #16]             // 16-byte Folded Spill
	mov	x19, x0
	mov	x29, sp
	cbnz	x0, .LBB5_3
// %bb.2:
	mov	w8, #24                         // =0x18
	ldr	x8, [x8]
	cbz	x8, .LBB5_15
.LBB5_3:
	adrp	x9, need_pic
	ldr	x11, [x19, #24]
	ldrb	w8, [x10, #38]
	str	w3, [x9, :lo12:need_pic]
	adrp	x9, waveformdata
	str	x11, [x9, :lo12:waveformdata]
	cbz	w8, .LBB5_9
// %bb.4:
	mov	x9, xzr
	add	x10, x10, #48
.LBB5_5:                                // =>This Inner Loop Header: Depth=1
	ldrb	w11, [x10, x9]
	cmp	w2, w11
	b.le	.LBB5_10
// %bb.6:                               //   in Loop: Header=BB5_5 Depth=1
	add	x9, x9, #1
	cmp	x8, x9
	b.ne	.LBB5_5
// %bb.7:
	mov	w10, #-1                        // =0xffffffff
	mov	w9, w8
	b	.LBB5_11
.LBB5_8:
	mov	w0, #-19                        // =0xffffffed
	ret
.LBB5_9:
	mov	w20, wzr
	b	.LBB5_12
.LBB5_10:
	mov	w10, w9
.LBB5_11:
	sub	w11, w9, #1
	cmp	w9, w8
	csel	w20, w11, w10, eq
.LBB5_12:
	mov	w0, w1
	bl	get_wf_mode_index
	and	w0, w0, #0xff
	mov	w1, w20
	bl	get_wf_frm_num
	tbnz	w0, #31, .LBB5_16
// %bb.13:
	mov	w8, w0
	mov	w0, wzr
	str	w8, [x19]
.LBB5_14:
	ldp	x20, x19, [sp, #16]             // 16-byte Folded Reload
	ldp	x29, x30, [sp], #32             // 16-byte Folded Reload
	ldr	x30, [x18, #-8]!
	ret
.LBB5_15:
	mov	w0, #-22                        // =0xffffffea
	b	.LBB5_14
.LBB5_16:
	adrp	x0, .L.str
	add	x0, x0, :lo12:.L.str
	bl	_printk
	mov	w0, #-5                         // =0xfffffffb
	b	.LBB5_14
.Lfunc_end5:
	.size	pvi_wf_get_original_lut, .Lfunc_end5-pvi_wf_get_original_lut
                                        // -- End function
	.globl	pvi_wf_input                    // -- Begin function pvi_wf_input
	.p2align	2
	.type	pvi_wf_input,@function
	.word	3228165220                      // 0xc069e464
pvi_wf_input:                           // @pvi_wf_input
// %bb.0:
	str	x30, [x18], #8
	stp	x29, x30, [sp, #-32]!           // 16-byte Folded Spill
	stp	x20, x19, [sp, #16]             // 16-byte Folded Spill
	adrp	x19, global_waveform
	mov	x29, sp
	ldr	x8, [x19, :lo12:global_waveform]
	cbz	x8, .LBB6_2
// %bb.1:
	mov	w0, #-16                        // =0xfffffff0
	b	.LBB6_17
.LBB6_2:
	ldrb	w1, [x0, #16]
	mov	w8, #32                         // =0x20
	cmp	w1, #66
	b.gt	.LBB6_8
// %bb.3:
	cmp	w1, #35
	b.hi	.LBB6_13
// %bb.4:
	cbnz	x1, .LBB6_6
// %bb.5:
	mov	w0, #-8                         // =0xfffffff8
	b	.LBB6_17
.LBB6_6:
	mov	w9, #1                          // =0x1
	mov	x10, #54525952                  // =0x3400000
	lsl	x9, x9, x1
	movk	x10, #1, lsl #32
	tst	x9, x10
	b.ne	.LBB6_15
// %bb.7:
	mov	w8, #1                          // =0x1
	mov	x9, #512                        // =0x200
	lsl	x8, x8, x1
	movk	x9, #4, lsl #16
	movk	x9, #8, lsl #32
	tst	x8, x9
	b.ne	.LBB6_16
	b	.LBB6_13
.LBB6_8:
	cmp	w1, #83
	b.gt	.LBB6_11
// %bb.9:
	cmp	w1, #67
	b.eq	.LBB6_15
// %bb.10:
	cmp	w1, #72
	b.eq	.LBB6_15
	b	.LBB6_13
.LBB6_11:
	cmp	w1, #84
	b.eq	.LBB6_16
// %bb.12:
	cmp	w1, #114
	b.eq	.LBB6_15
.LBB6_13:
	adrp	x8, custom_mode_table+9
	ldrb	w8, [x8, :lo12:custom_mode_table+9]
	cmp	w1, w8
	b.ne	.LBB6_18
// %bb.14:
	adrp	x8, custom_mode_table+12
	ldr	w8, [x8, :lo12:custom_mode_table+12]
.LBB6_15:
	adrp	x9, maxpic
	str	w8, [x9, :lo12:maxpic]
.LBB6_16:
	adrp	x8, maxpic
	mov	x20, x0
                                        // kill: def $w1 killed $w1 killed $x1
	ldr	w2, [x8, :lo12:maxpic]
	adrp	x8, .L.str.2
	add	x8, x8, :lo12:.L.str.2
	mov	x0, x8
	bl	_printk
	mov	w0, wzr
	str	x20, [x19, :lo12:global_waveform]
.LBB6_17:
	ldp	x20, x19, [sp, #16]             // 16-byte Folded Reload
	ldp	x29, x30, [sp], #32             // 16-byte Folded Reload
	ldr	x30, [x18, #-8]!
	ret
.LBB6_18:
	ldrb	w2, [x0, #22]
	adrp	x0, .L.str.1
	add	x0, x0, :lo12:.L.str.1
                                        // kill: def $w1 killed $w1 killed $x1
	bl	_printk
	mov	w0, #-8                         // =0xfffffff8
	b	.LBB6_17
.Lfunc_end6:
	.size	pvi_wf_input, .Lfunc_end6-pvi_wf_input
                                        // -- End function
	.globl	pvi_wf_get_version              // -- Begin function pvi_wf_get_version
	.p2align	2
	.type	pvi_wf_get_version,@function
	.word	1371061343                      // 0x51b8bc5f
pvi_wf_get_version:                     // @pvi_wf_get_version
// %bb.0:
	adrp	x8, global_waveform
	ldr	x9, [x8, :lo12:global_waveform]
	cbz	x9, .LBB7_5
// %bb.1:
	ldrb	w10, [x9, #64]
	mov	w8, #63                         // =0x3f
	adrp	x0, pvi_wf_get_version.spi_id_buffer
	add	x0, x0, :lo12:pvi_wf_get_version.spi_id_buffer
	cmp	w10, #63
	csel	w8, w10, w8, lo
	cbz	w10, .LBB7_4
// %bb.2:
	add	x9, x9, #65
	adrp	x10, pvi_wf_get_version.spi_id_buffer
	add	x10, x10, :lo12:pvi_wf_get_version.spi_id_buffer
	mov	x11, x8
.LBB7_3:                                // =>This Inner Loop Header: Depth=1
	ldrb	w12, [x9], #1
	subs	x11, x11, #1
	strb	w12, [x10], #1
	b.ne	.LBB7_3
.LBB7_4:
	add	x8, x0, w8, uxtw
	strb	wzr, [x8, #1]
	ret
.LBB7_5:
	mov	x0, xzr
	ret
.Lfunc_end7:
	.size	pvi_wf_get_version, .Lfunc_end7-pvi_wf_get_version
                                        // -- End function
	.globl	pvi_wf_get_wf_bit               // -- Begin function pvi_wf_get_wf_bit
	.p2align	2
	.type	pvi_wf_get_wf_bit,@function
	.word	1874538549                      // 0x6fbb3035
pvi_wf_get_wf_bit:                      // @pvi_wf_get_wf_bit
// %bb.0:
	adrp	x8, global_waveform
	adrp	x9, maxpic
	ldr	x8, [x8, :lo12:global_waveform]
	ldr	w9, [x9, :lo12:maxpic]
	cmp	x8, #0
	csel	w0, wzr, w9, eq
	ret
.Lfunc_end8:
	.size	pvi_wf_get_wf_bit, .Lfunc_end8-pvi_wf_get_wf_bit
                                        // -- End function
	.type	pvi_mode_table,@object          // @pvi_mode_table
	.section	.rodata,"a",@progbits
	.globl	pvi_mode_table
pvi_mode_table:
	.ascii	"\000\001\001\002\003\003\003\004\003"
	.ascii	"\000\001\007\003\003\005\006\004\005"
	.ascii	"\000\001\001\002\003\004\004\006\005"
	.ascii	"\000\001\007\002\003\004\005\006\004"
	.ascii	"\000\001\005\002\003\003\003\004\003"
	.ascii	"\000\001\001\002\003\004\004\006\004"
	.ascii	"\000\001\001\002\003\004\004\005\004"
	.ascii	"\000\001\001\002\003\004\013\006\n"
	.ascii	"\000\001\001\002\003\004\005\006\004"
	.size	pvi_mode_table, 81

	.type	custom_mode_table,@object       // @custom_mode_table
	.bss
	.globl	custom_mode_table
	.p2align	2, 0x0
custom_mode_table:
	.zero	16
	.size	custom_mode_table, 16

	.type	pvi_wf_get_lut.stype,@object    // @pvi_wf_get_lut.stype
	.data
	.p2align	2, 0x0
pvi_wf_get_lut.stype:
	.word	16                              // 0x10
	.size	pvi_wf_get_lut.stype, 4

	.type	pvi_wf_get_lut.sftemp,@object   // @pvi_wf_get_lut.sftemp
	.p2align	2, 0x0
pvi_wf_get_lut.sftemp:
	.word	4294967295                      // 0xffffffff
	.size	pvi_wf_get_lut.sftemp, 4

	.type	pvi_wf_get_lut.normal_repair,@object // @pvi_wf_get_lut.normal_repair
	.local	pvi_wf_get_lut.normal_repair
	.comm	pvi_wf_get_lut.normal_repair,4,4
	.type	global_waveform,@object         // @global_waveform
	.local	global_waveform
	.comm	global_waveform,8,8
	.type	need_pic,@object                // @need_pic
	.p2align	2, 0x0
need_pic:
	.word	16                              // 0x10
	.size	need_pic, 4

	.type	waveformdata,@object            // @waveformdata
	.local	waveformdata
	.comm	waveformdata,8,8
	.type	.L.str,@object                  // @.str
	.section	.rodata.str1.1,"aMS",@progbits,1
.L.str:
	.asciz	"pvi waveform get frame number failed\n"
	.size	.L.str, 38

	.type	maxpic,@object                  // @maxpic
	.data
	.p2align	2, 0x0
maxpic:
	.word	16                              // 0x10
	.size	maxpic, 4

	.type	.L.str.1,@object                // @.str.1
	.section	.rodata.str1.1,"aMS",@progbits,1
.L.str.1:
	.asciz	"pvi : Unknow waveform version 0x%x, 0x%x, may be wrong waveform file\n"
	.size	.L.str.1, 70

	.type	.L.str.2,@object                // @.str.2
.L.str.2:
	.asciz	"pvi : input waveform version 0x%x, gray level: %d\n"
	.size	.L.str.2, 51

	.type	pvi_wf_get_version.spi_id_buffer,@object // @pvi_wf_get_version.spi_id_buffer
	.local	pvi_wf_get_version.spi_id_buffer
	.comm	pvi_wf_get_version.spi_id_buffer,64,1
	.type	.L.str.3,@object                // @.str.3
.L.str.3:
	.asciz	"pvi: unspport PVI waveform type"
	.size	.L.str.3, 32

	.type	.L.str.4,@object                // @.str.4
.L.str.4:
	.asciz	"pvi: %s %d check error\n"
	.size	.L.str.4, 24

	.type	.L__func__.get_wf_frm_num,@object // @__func__.get_wf_frm_num
.L__func__.get_wf_frm_num:
	.asciz	"get_wf_frm_num"
	.size	.L__func__.get_wf_frm_num, 15

	.type	.L.str.5,@object                // @.str.5
.L.str.5:
	.asciz	"waveformdata is NULL\n"
	.size	.L.str.5, 22

	.type	.L.str.6,@object                // @.str.6
.L.str.6:
	.asciz	"pvi: decodec waveform error, framenum err\n"
	.size	.L.str.6, 43

	.type	.Lswitch.table.get_wf_mode_index,@object // @switch.table.get_wf_mode_index
	.section	.rodata,"a",@progbits
	.p2align	3, 0x0
.Lswitch.table.get_wf_mode_index:
	.xword	5                               // 0x5
	.xword	6                               // 0x6
	.xword	4                               // 0x4
	.xword	3                               // 0x3
	.xword	5                               // 0x5
	.size	.Lswitch.table.get_wf_mode_index, 40

	.ident	"Android (13290119, +pgo, +bolt, +lto, +mlgo, based on r547379) clang version 20.0.0 (https://android.googlesource.com/toolchain/llvm-project b718bcaf8c198c82f3021447d943401e3ab5bd54)"
	.section	".note.GNU-stack","",@progbits
	.addrsig
	.addrsig_sym pvi_wf_get_version.spi_id_buffer
